package io.resupply.karoo.data

import io.resupply.karoo.BuildConfig
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.OkHttpClient
import okhttp3.Request
import timber.log.Timber
import java.util.concurrent.TimeUnit

/**
 * Checks whether a newer release of the app is available and where to get its APK.
 *
 * It reads the release `manifest.json` generated by the `generateManifest` Gradle task, but it
 * must find the *app* release to read it from. We can't use the `releases/latest/download/` alias
 * the Karoo store uses: GitHub resolves `/latest/` to the newest release *by date*, and the
 * frequently-republished `regions-latest` catalog release is almost always newer than the app
 * release — so the alias redirects to the 40 KB regions catalog, not the ~2 KB app manifest. (That
 * also overflows the Karoo bridge's response-size cap; see [io.resupply.karoo.util.httpRequest].)
 *
 * So we resolve the newest app release explicitly through the GitHub releases API: list releases
 * (newest-first), pick the first whose tag looks like `vX.Y.Z`, and read that release's
 * `manifest.json` asset. Both calls go over a direct OkHttp (WiFi) connection — no bridge, so no
 * size cap and no redirect trouble. The caller gates this on WiFi; the APK download in
 * [io.resupply.karoo.service.AppUpdateService] already requires WiFi too.
 */
class AppUpdateClient {

    private val json = Json { ignoreUnknownKeys = true }

    private val client = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .build()

    /**
     * Resolve the newest app release and fetch its app manifest. Returns null on any
     * network/parse failure, or if no `vX.Y.Z` release carries a `manifest.json` asset. Must be
     * called off the main thread (blocking OkHttp); callers run it in a coroutine on IO.
     */
    fun fetchManifest(): AppManifest? {
        val manifestUrl = resolveAppManifestUrl() ?: return null
        val body = get(manifestUrl) ?: return null
        return runCatching {
            json.decodeFromString<AppManifest>(body)
        }.onFailure { Timber.e(it, "app manifest parse failed") }.getOrNull()
    }

    /** Newest `vX.Y.Z` release's `manifest.json` asset URL, or null. */
    private fun resolveAppManifestUrl(): String? {
        val body = get(RELEASES_API_URL) ?: return null
        val releases = runCatching {
            json.decodeFromString<List<GitHubRelease>>(body)
        }.onFailure { Timber.e(it, "releases listing parse failed") }.getOrNull() ?: return null

        val appRelease = releases.firstOrNull { APP_TAG.matches(it.tagName) }
        if (appRelease == null) {
            Timber.d("no vX.Y.Z app release found in releases listing")
            return null
        }
        val url = appRelease.assets.firstOrNull { it.name == "manifest.json" }?.downloadUrl
        if (url == null) Timber.d("app release ${appRelease.tagName} has no manifest.json asset")
        return url
    }

    /** One-shot GET returning the body as a string, or null on any non-2xx / IO failure. */
    private fun get(url: String): String? =
        runCatching {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                if (!response.isSuccessful) {
                    Timber.d("app update GET ${response.code} for $url")
                    return null
                }
                response.body?.string()
            }
        }.onFailure { Timber.d(it, "app update GET failed for $url") }.getOrNull()

    companion object {
        /** Newest-first releases listing; 30 is plenty to reach past the regions release. */
        const val RELEASES_API_URL =
            "https://api.github.com/repos/patricebender/resupply-karoo/releases?per_page=30"

        /** App release tags are `vMAJOR.MINOR.PATCH` (matched in full — `matches` requires the
         *  whole string); the regions catalog tag (`regions-latest`) and any other non-app tags
         *  don't match, so they're skipped. */
        private val APP_TAG = Regex("""v\d+\.\d+\.\d+""")

        /** True if [manifest] describes a build newer than the running one. */
        fun isNewer(manifest: AppManifest): Boolean =
            manifest.latestVersionCode > BuildConfig.VERSION_CODE
    }
}

/** The subset of a GitHub release the updater reads to find the app manifest asset. */
@Serializable
private data class GitHubRelease(
    @kotlinx.serialization.SerialName("tag_name") val tagName: String,
    val assets: List<GitHubAsset> = emptyList(),
)

@Serializable
private data class GitHubAsset(
    val name: String,
    @kotlinx.serialization.SerialName("browser_download_url") val downloadUrl: String,
)

/**
 * The app self-update view of the release `manifest.json`. Only the fields the updater
 * reads are modelled; the rest (label, iconUrl, screenshots, …) are tolerated via
 * `ignoreUnknownKeys`.
 */
@Serializable
data class AppManifest(
    val latestVersion: String,
    val latestVersionCode: Int,
    val latestApkUrl: String,
    /** First bullets of the newest CHANGELOG entry; shown as "what's new". */
    val releaseNotes: String = "",
)
