package io.resupply.karoo.data

import io.hammerhead.karooext.KarooSystemService
import io.resupply.karoo.BuildConfig
import io.resupply.karoo.util.httpRequest
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import timber.log.Timber

/**
 * Checks whether a newer release of the app is available and where to get its APK, by
 * reading the same `manifest.json` the Karoo Extensions library uses (attached to the
 * GitHub release, generated by the `generateManifest` Gradle task). The manifest is small
 * JSON, so it goes through the Karoo HTTP bridge like [RegionCatalogClient.fetchManifest] —
 * it works over the paired phone, not just WiFi. The APK download itself needs the direct
 * WiFi path (see [io.resupply.karoo.service.AppUpdateService]); the bridge's ~100 KB cap
 * rules it out for a multi-MB APK.
 */
class AppUpdateClient(private val system: KarooSystemService) {

    private val json = Json { ignoreUnknownKeys = true }

    /** Fetch and parse the app manifest; null on any network/parse failure. */
    suspend fun fetchManifest(): AppManifest? {
        val complete = system.httpRequest(method = "GET", url = APP_MANIFEST_URL) ?: return null
        val body = complete.body
        if (complete.statusCode !in 200..299 || body == null) {
            Timber.d("app manifest fetch failed: ${complete.statusCode} ${complete.error}")
            return null
        }
        return runCatching {
            json.decodeFromString<AppManifest>(body.decodeToString())
        }.onFailure { Timber.e(it, "app manifest parse failed") }.getOrNull()
    }

    companion object {
        /**
         * The `latest/download` alias always resolves to the newest release's assets, so a
         * check here means "is there a release newer than what's installed?". Matches the
         * `$BASE_URL$` the AndroidManifest points the Karoo store at.
         */
        const val APP_MANIFEST_URL =
            "https://github.com/patricebender/resupply-karoo/releases/latest/download/manifest.json"

        /** True if [manifest] describes a build newer than the running one. */
        fun isNewer(manifest: AppManifest): Boolean =
            manifest.latestVersionCode > BuildConfig.VERSION_CODE
    }
}

/**
 * The app self-update view of the release `manifest.json`. Only the fields the updater
 * reads are modelled; the rest (label, iconUrl, screenshots, …) are tolerated via
 * `ignoreUnknownKeys`.
 */
@Serializable
data class AppManifest(
    val latestVersion: String,
    val latestVersionCode: Int,
    val latestApkUrl: String,
    /** First bullets of the newest CHANGELOG entry; shown as "what's new". */
    val releaseNotes: String = "",
)
